---
- name: Install essential packages on Ubuntu/Debian
  hosts: all
  become: true
  gather_facts: false

  vars:
    packages:
      - vim
      - curl
      - unzip

  tasks:
    - name: Update apt cache and install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
